global:
  scrape_interval: "10s"
  scrape_timeout: "10s"
  evaluation_interval: "10s"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      api_version: v2
      path_prefix: /
      scheme: http
      static_configs:
        - targets: ["alertmanagers:59093"]

scrape_configs:
  - job_name: kafka-controllers
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["kafka-controller-1:9300","kafka-controller-2:9300","kafka-controller-3:9300"]
  
  - job_name: kafka-brokers
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["kafka-broker-1:9300","kafka-broker-2:9300","kafka-broker-3:9300"]
  
  - job_name: spark-master-workers
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["spark-master:9300","spark-worker:9300","spark-worker-2:9300"]